"""add payload to notifications

Revision ID: 07f4032d4830
Revises: 93f46f261589
Create Date: 2026-02-10 08:26:40.739219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '07f4032d4830'
down_revision: Union[str, Sequence[str], None] = '93f46f261589'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    "moderations",
    sa.Column("is_admin", sa.Boolean(), nullable=True),
    )

    # Backfill existing rows
    # 1️⃣ Convert ENUM → TEXT
    op.execute("""
        ALTER TABLE moderations
        ALTER COLUMN new_status
        TYPE TEXT
        USING new_status::text
    """)

    # 2️⃣ Convert TEXT → contentstatus ENUM
    op.execute("""
        ALTER TABLE moderations
        ALTER COLUMN new_status
        TYPE contentstatus
        USING new_status::contentstatus
    """)
    op.alter_column('moderations', 'reason',
               existing_type=sa.TEXT(),
               nullable=True)
    op.add_column('notifications', sa.Column('payload', sa.JSON(), nullable=False))
    op.alter_column('notifications', 'type',
               existing_type=postgresql.ENUM('reply', 'evidence_added', name='notification_type'),
               type_=sa.Text(),
               existing_nullable=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.drop_constraint(op.f('notifications_user_id_fkey'), 'notifications', type_='foreignkey')
    op.drop_column('notifications', 'reference_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('reference_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('notifications_user_id_fkey'), 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.alter_column('notifications', 'type',
               existing_type=sa.Text(),
               type_=postgresql.ENUM('reply', 'evidence_added', name='notification_type'),
               existing_nullable=False)
    op.drop_column('notifications', 'payload')
    op.alter_column('moderations', 'reason',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('moderations', 'new_status',
               existing_type=sa.Enum('active', 'locked', 'removed_illegal', name='contentstatus'),
               type_=postgresql.ENUM('removed_illegal', 'locked', name='moderation_action'),
               existing_nullable=False)
    op.drop_column('moderations', 'is_admin')
    # ### end Alembic commands ###
