"""add evidence tamper detection

Revision ID: 126bf9ca78bd
Revises: 9e1f4d087a36
Create Date: 2026-03-15 12:38:54.863467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '126bf9ca78bd'
down_revision: Union[str, Sequence[str], None] = '9e1f4d087a36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "evidence",
        sa.Column(
            "tampered",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False
        )
    )
    op.alter_column("evidence", "tampered", server_default=None)


    op.add_column('evidence', sa.Column('last_verified_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evidence', 'last_verified_at')
    op.drop_column('evidence', 'tampered')
    # ### end Alembic commands ###
