"""add feed scaling indexes

Revision ID: 1439f7d2371d
Revises: c64a167018b4
Create Date: 2026-02-16 07:49:17.501614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1439f7d2371d'
down_revision: Union[str, Sequence[str], None] = 'c64a167018b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_post_like'), 'post_likes', type_='unique')
    op.create_index('idx_post_likes_post_created', 'post_likes', ['post_id', 'created_at'], unique=False)
    op.create_index('idx_posts_status_created_at', 'posts', ['status', 'created_at'], unique=False)
    op.create_index('idx_replies_post_created', 'replies', ['post_id', 'created_at'], unique=False)
    op.drop_constraint(op.f('uq_reply_like'), 'reply_likes', type_='unique')
    op.create_index('idx_reply_likes_reply_created', 'reply_likes', ['reply_id', 'created_at'], unique=False)
    op.create_unique_constraint('uq_reply_like_user', 'reply_likes', ['reply_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_reply_like_user', 'reply_likes', type_='unique')
    op.drop_index('idx_reply_likes_reply_created', table_name='reply_likes')
    op.create_unique_constraint(op.f('uq_reply_like'), 'reply_likes', ['reply_id', 'user_id'], postgresql_nulls_not_distinct=False)
    op.drop_index('idx_replies_post_created', table_name='replies')
    op.drop_index('idx_posts_status_created_at', table_name='posts')
    op.drop_index('idx_post_likes_post_created', table_name='post_likes')
    op.create_unique_constraint(op.f('uq_post_like'), 'post_likes', ['post_id', 'user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
