"""Add Source Relationship to Evidence

Revision ID: 21b2f33ef5d2
Revises: 36479634d26b
Create Date: 2026-03-15 13:18:43.779991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21b2f33ef5d2'
down_revision: Union[str, Sequence[str], None] = '36479634d26b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evidence', sa.Column('source_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'evidence', 'sources', ['source_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'evidence', type_='foreignkey')
    op.drop_column('evidence', 'source_id')
    # ### end Alembic commands ###
