"""add source reputation intelligence fields

Revision ID: 24ed8ce964e0
Revises: 21b2f33ef5d2
Create Date: 2026-03-15 13:24:34.360436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24ed8ce964e0'
down_revision: Union[str, Sequence[str], None] = '21b2f33ef5d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('accuracy_score', sa.Float(), nullable=True))
    op.add_column('sources', sa.Column('contradiction_rate', sa.Float(), nullable=True))
    op.add_column('sources', sa.Column('tamper_events', sa.Integer(), nullable=False))
    op.add_column('sources', sa.Column('citation_count', sa.Integer(), nullable=False))
    op.add_column('sources', sa.Column('last_evaluated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'last_evaluated_at')
    op.drop_column('sources', 'citation_count')
    op.drop_column('sources', 'tamper_events')
    op.drop_column('sources', 'contradiction_rate')
    op.drop_column('sources', 'accuracy_score')
    # ### end Alembic commands ###
