"""add evidence credibility score

Revision ID: 2a8a9562825d
Revises: 126bf9ca78bd
Create Date: 2026-03-15 12:58:34.284545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a8a9562825d'
down_revision: Union[str, Sequence[str], None] = '126bf9ca78bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evidence', sa.Column('credibility_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evidence', 'credibility_score')
    # ### end Alembic commands ###
