"""add truth scoring to posts

Revision ID: 36479634d26b
Revises: 2a8a9562825d
Create Date: 2026-03-15 13:13:45.810614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36479634d26b'
down_revision: Union[str, Sequence[str], None] = '2a8a9562825d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('truth_score', sa.Float(), nullable=True))
    op.add_column('posts', sa.Column('truth_confidence', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'truth_confidence')
    op.drop_column('posts', 'truth_score')
    # ### end Alembic commands ###
