"""fix refresh token schema

Revision ID: 4d161cbcb561
Revises: ee77f7051f58
Create Date: 2026-02-27 10:39:43.650584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d161cbcb561'
down_revision: Union[str, Sequence[str], None] = 'ee77f7051f58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refresh_tokens', 'is_revoked',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_index(op.f('ix_refresh_tokens_replaced_by'), 'refresh_tokens', ['replaced_by'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=False)
    op.create_foreign_key(None, 'refresh_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_replaced_by'), table_name='refresh_tokens')
    op.alter_column('refresh_tokens', 'is_revoked',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
