"""expand evidence model

Revision ID: 55e0818601db
Revises: 13bf1d30e407
Create Date: 2026-02-07 17:39:52.758614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

evidence_type_enum = postgresql.ENUM(
    "link",
    "document",
    "image",
    "quote",
    name="evidence_type",
)

evidence_direction_enum = postgresql.ENUM(
    "supports",
    "contradicts",
    name="evidence_direction",
)



# revision identifiers, used by Alembic.
revision: str = '55e0818601db'
down_revision: Union[str, Sequence[str], None] = '13bf1d30e407'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    evidence_type_enum.create(op.get_bind(), checkfirst=True)
    evidence_direction_enum.create(op.get_bind(), checkfirst=True)

    op.add_column(
        "evidence",
        sa.Column("submitted_by", sa.UUID(), nullable=False),
    )
    op.add_column(
        "evidence",
        sa.Column("evidence_type", evidence_type_enum, nullable=False),
    )
    op.add_column(
        "evidence",
        sa.Column("source_url", sa.Text(), nullable=True),
    )
    op.add_column(
        "evidence",
        sa.Column("upload_path", sa.Text(), nullable=True),
    )
    op.add_column(
        "evidence",
        sa.Column("source_description", sa.Text(), nullable=False),
    )
    op.add_column(
        "evidence",
        sa.Column("direction", evidence_direction_enum, nullable=False),
    )
    op.add_column(
        "evidence",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )

    op.create_index("ix_evidence_direction", "evidence", ["direction"])
    op.create_index("ix_evidence_post_id", "evidence", ["post_id"])

    op.drop_constraint("evidence_post_id_fkey", "evidence", type_="foreignkey")

    op.create_foreign_key(
        "fk_evidence_submitted_by_users",
        "evidence",
        "users",
        ["submitted_by"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        "fk_evidence_post_id_posts",
        "evidence",
        "posts",
        ["post_id"],
        ["id"],
        ondelete="CASCADE",
    )

    op.drop_column("evidence", "content")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evidence', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint("fk_evidence_post_id_posts", "evidence", type_="foreignkey")
    op.drop_constraint("fk_evidence_submitted_by_users", "evidence", type_="foreignkey")
    op.create_foreign_key(op.f('evidence_post_id_fkey'), 'evidence', 'posts', ['post_id'], ['id'])
    op.drop_index('ix_evidence_post_id', table_name='evidence')
    op.drop_index('ix_evidence_direction', table_name='evidence')
    op.drop_column('evidence', 'created_at')
    op.drop_column('evidence', 'direction')
    op.drop_column('evidence', 'source_description')
    op.drop_column('evidence', 'upload_path')
    op.drop_column('evidence', 'source_url')
    op.drop_column('evidence', 'evidence_type')
    op.drop_column('evidence', 'submitted_by')
    evidence_direction_enum.drop(op.get_bind(), checkfirst=True)
    evidence_type_enum.drop(op.get_bind(), checkfirst=True)

    # ### end Alembic commands ###
