"""add id to post index

Revision ID: 66edecbf8351
Revises: 960a41207de4
Create Date: 2026-02-18 18:31:06.093160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66edecbf8351'
down_revision: Union[str, Sequence[str], None] = '960a41207de4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_posts_status_created_at'), table_name='posts')
    op.create_index('idx_posts_status_created_at', 'posts', ['status', 'created_at', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_posts_status_created_at', table_name='posts')
    op.create_index(op.f('idx_posts_status_created_at'), 'posts', ['status', 'created_at'], unique=False)
    # ### end Alembic commands ###
