"""add notifications table

Revision ID: 794a43a170ba
Revises: 44c7ae592dba
Create Date: 2026-02-07 18:28:47.784213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '794a43a170ba'
down_revision: Union[str, Sequence[str], None] = '44c7ae592dba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_moderations_target'), table_name='moderations')
    op.drop_constraint(op.f('moderations_post_id_fkey'), 'moderations', type_='foreignkey')
    op.drop_column('moderations', 'content')
    op.drop_column('moderations', 'post_id')
    op.add_column('notifications', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('notifications', sa.Column('type', sa.Enum('reply', 'evidence_added', name='notification_type'), nullable=False))
    op.add_column('notifications', sa.Column('reference_id', sa.UUID(), nullable=False))
    op.add_column('notifications', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('notifications', sa.Column('read_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('notifications_post_id_fkey'), 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('notifications', 'content')
    op.drop_column('notifications', 'post_id')
    op.add_column('replies', sa.Column('body', sa.Text(), nullable=False))
    op.drop_constraint(op.f('replies_post_id_fkey'), 'replies', type_='foreignkey')
    op.create_foreign_key(None, 'replies', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.drop_column('replies', 'content')
    op.drop_index(op.f('ix_reports_target'), table_name='reports')
    op.drop_constraint(op.f('reports_post_id_fkey'), 'reports', type_='foreignkey')
    op.drop_column('reports', 'content')
    op.drop_column('reports', 'post_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('post_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('reports', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('reports_post_id_fkey'), 'reports', 'posts', ['post_id'], ['id'])
    op.create_index(op.f('ix_reports_target'), 'reports', ['target_type', 'target_id'], unique=False)
    op.add_column('replies', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'replies', type_='foreignkey')
    op.create_foreign_key(op.f('replies_post_id_fkey'), 'replies', 'posts', ['post_id'], ['id'])
    op.drop_column('replies', 'body')
    op.add_column('notifications', sa.Column('post_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('notifications', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key(op.f('notifications_post_id_fkey'), 'notifications', 'posts', ['post_id'], ['id'])
    op.drop_column('notifications', 'read_at')
    op.drop_column('notifications', 'created_at')
    op.drop_column('notifications', 'reference_id')
    op.drop_column('notifications', 'type')
    op.drop_column('notifications', 'user_id')
    op.add_column('moderations', sa.Column('post_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('moderations', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('moderations_post_id_fkey'), 'moderations', 'posts', ['post_id'], ['id'])
    op.create_index(op.f('ix_moderations_target'), 'moderations', ['target_type', 'target_id'], unique=False)
    # ### end Alembic commands ###
