"""add like and reply counters

Revision ID: 88d56e849ff5
Revises: 1439f7d2371d
Create Date: 2026-02-18 12:14:49.995115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88d56e849ff5'
down_revision: Union[str, Sequence[str], None] = '1439f7d2371d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('like_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('posts', sa.Column('reply_count', sa.Integer(), server_default='0', nullable=False))
    op.create_index('idx_posts_like_count', 'posts', ['like_count'], unique=False)
    op.add_column('replies', sa.Column('like_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('replies', 'like_count')
    op.drop_index('idx_posts_like_count', table_name='posts')
    op.drop_column('posts', 'reply_count')
    op.drop_column('posts', 'like_count')
    # ### end Alembic commands ###
