"""add evidence provenance tracking

Revision ID: 9e1f4d087a36
Revises: bdceba147cf0
Create Date: 2026-03-15 12:20:51.668337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9e1f4d087a36'
down_revision: Union[str, Sequence[str], None] = 'bdceba147cf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evidence', sa.Column('archived_content', sa.Text(), nullable=True))
    op.add_column('evidence', sa.Column('archived_at', sa.DateTime(), nullable=True))
    op.add_column(
        "evidence",
        sa.Column(
            "archive_version",
            sa.Integer(),
            server_default="1",
            nullable=False
        )
    )
    op.alter_column("evidence", "archive_version", server_default=None)

    op.drop_index(op.f('ix_evidence_source_id'), table_name='evidence')
    op.drop_constraint(op.f('evidence_source_id_fkey'), 'evidence', type_='foreignkey')
    op.drop_column('evidence', 'source_id')
    op.drop_column('evidence', 'archive_url')
    op.drop_column('evidence', 'retrieved_at')
    op.drop_column('evidence', 'weight')
    op.drop_column('posts', 'truth_score')
    op.drop_column('posts', 'truth_confidence')
    op.add_column('sources', sa.Column('source_id', sa.UUID(), nullable=True))
    op.add_column('sources', sa.Column('weight', sa.Float(), nullable=False))
    op.create_index(op.f('ix_sources_source_id'), 'sources', ['source_id'], unique=False)
    op.create_foreign_key(None, 'sources', 'sources', ['source_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sources', type_='foreignkey')
    op.drop_index(op.f('ix_sources_source_id'), table_name='sources')
    op.drop_column('sources', 'weight')
    op.drop_column('sources', 'source_id')
    op.add_column('posts', sa.Column('truth_confidence', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('posts', sa.Column('truth_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('evidence', sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('evidence', sa.Column('retrieved_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('evidence', sa.Column('archive_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('evidence', sa.Column('source_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('evidence_source_id_fkey'), 'evidence', 'sources', ['source_id'], ['id'])
    op.create_index(op.f('ix_evidence_source_id'), 'evidence', ['source_id'], unique=False)
    op.drop_column('evidence', 'archive_version')
    op.drop_column('evidence', 'archived_at')
    op.drop_column('evidence', 'archived_content')
    # ### end Alembic commands ###
