"""add narrative intelligence fields

Revision ID: a1b2c08daf6c
Revises: 24ed8ce964e0
Create Date: 2026-03-15 13:29:47.063876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c08daf6c'
down_revision: Union[str, Sequence[str], None] = '24ed8ce964e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('narrative_cluster_id', sa.String(), nullable=True))
    op.add_column('posts', sa.Column('narrative_risk_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'narrative_risk_score')
    op.drop_column('posts', 'narrative_cluster_id')
    # ### end Alembic commands ###
