"""added columns to refresh_token model

Revision ID: aee85bd1dd2a
Revises: cf16e91c296d
Create Date: 2026-02-20 21:04:16.385006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aee85bd1dd2a'
down_revision: Union[str, Sequence[str], None] = 'cf16e91c296d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('device_name', sa.String(), nullable=True))
    op.add_column('refresh_tokens', sa.Column('ip_address', sa.String(), nullable=True))
    op.add_column('refresh_tokens', sa.Column('user_agent', sa.String(), nullable=True))
    op.add_column('refresh_tokens', sa.Column('last_used_at', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_tokens', 'last_used_at')
    op.drop_column('refresh_tokens', 'user_agent')
    op.drop_column('refresh_tokens', 'ip_address')
    op.drop_column('refresh_tokens', 'device_name')
    # ### end Alembic commands ###
