"""added password_reset_token_hash and password_reset_expires columns in user model

Revision ID: cf16e91c296d
Revises: 37b1f0534f11
Create Date: 2026-02-20 20:27:31.580141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf16e91c296d'
down_revision: Union[str, Sequence[str], None] = '37b1f0534f11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_reset_token_hash', sa.String(), nullable=True))
    op.add_column('users', sa.Column('password_reset_expires', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_reset_expires')
    op.drop_column('users', 'password_reset_token_hash')
    # ### end Alembic commands ###
