"""add like tables

Revision ID: db4751978195
Revises: 07f4032d4830
Create Date: 2026-02-12 06:43:50.527748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db4751978195'
down_revision: Union[str, Sequence[str], None] = '07f4032d4830'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        UPDATE moderations
        SET is_admin = FALSE
        WHERE is_admin IS NULL
        """
    )
    op.alter_column(
        'moderations',
        'is_admin',
        existing_type=sa.BOOLEAN(),
        nullable=False
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index('ix_notifications_user_unread', 'notifications', ['user_id', 'read_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notifications_user_unread', table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.alter_column('moderations', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
