"""added is_revoked and replaced_by columns in refresh_token model

Revision ID: ee77f7051f58
Revises: 57b0a4bf7d85
Create Date: 2026-02-25 13:35:40.185531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee77f7051f58'
down_revision: Union[str, Sequence[str], None] = '57b0a4bf7d85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('is_revoked', sa.Boolean(), nullable=True))
    op.add_column('refresh_tokens', sa.Column('replaced_by', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_tokens', 'replaced_by')
    op.drop_column('refresh_tokens', 'is_revoked')
    # ### end Alembic commands ###
