"""add claim clustering fields

Revision ID: fe67cc6913cb
Revises: a1b2c08daf6c
Create Date: 2026-03-15 16:02:06.042043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe67cc6913cb'
down_revision: Union[str, Sequence[str], None] = 'a1b2c08daf6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('claim_cluster_id', sa.String(), nullable=True))
    op.add_column('posts', sa.Column('claim_similarity_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'claim_similarity_score')
    op.drop_column('posts', 'claim_cluster_id')
    # ### end Alembic commands ###
